### ISSUE TITLE
Sourcify does not display because X-FRAME-OPTIONS set to "SAMEORIGIN"

### ISSUE THREAD

**Issue by sxbady** [ethereum/sourcify#892] opened 2023-01-17 07:52 UTC
Sourcify does not work in debugging contract and fetching contract source code because the X-FRAME-OPTIONS is set to "SAMEORIGIN". Could anyone help with this please?
![image](https://user-images.githubusercontent.com/103167456/212840651-dce38b14-caeb-45e2-a0d4-f5fd63527fbf.png)

**Comment by sxbady** [comment] 2023-01-17 11:57
I guess the call is made when I check the "Use generated sources (Solidity >= v0.7.2)" on the debugger window. But the Sourcify plugin doesn't display at all. 
![image](https://user-images.githubusercontent.com/103167456/212893058-8bc677d1-0e7f-47a0-9fae-d58287872056.png)

**Comment by kuzdogan** [comment] 2023-01-17 12:10
I am not really sure what might be causing this. From what I understand you are not using the Sourcify plugin but the debugger. It seems to be more related to the Remix debugger than the Sourcify plugin.

Can you please open this issue in the [Remix repo](https://github.com/ethereum/remix-project/issues) with some details?

**Comment by kuzdogan** [comment] 2023-03-13 18:36
Closing as no further information was provided and it wasn't possible to reproduce the error. I believe it was a temporary problem in Remix

**Closed by kuzdogan** 2023-03-13 18:36 UTC
