### ISSUE TITLE
Error: There are currently no pending contracts.

### ISSUE THREAD

**Issue by wfkhrrzi** [ethereum/sourcify#1770] opened 2024-12-05 06:04 UTC
Hi Devs,

I'm currently trying to self-host both Sourcify's UI & server. 

When I try to verify a contract through the UI, it returns `Error: There are currently no pending contracts.` when running `/session/verify-validated`, as per the image below.
![image](https://github.com/user-attachments/assets/15e81b00-4f23-4ee5-b23c-214e5b54bb80)

This is the log returned from the server:
```
2024-12-05T05:27:43.140Z [debug] [Server] verifyContractsInSession: iterate contract - contractId=1af1d997e50ce5c5b0ed07fedde1ce03d6e1c260 | contract=GamePlayerOpsFacet | address=undefined | chainId=undefined - [traceId=f2608569-64f9-43ef-ae73-8287c3507819]

2024-12-05T05:27:43.140Z [debug] [Server] verifyContractsInSession: not verifiable - contractId=1af1d997e50ce5c5b0ed07fedde1ce03d6e1c260 - [traceId=f2608569-64f9-43ef-ae73-8287c3507819]

2024-12-05T05:28:50.854Z [debug] [Server] checkAllByChainAndAddresses - chainIds=["1337","31337","56","97"] | addresses=["0x8aAba705bb48Bc8d36c761fB51bA79d931cA9eb8"] - [traceId=0f43f879-2c9c-4ef3-817b-5c47e49deb25]

2024-12-05T05:28:50.868Z [debug] [Server] Result checkAllByChainAndAddresses - resultArray=[{"address":"0x8aAba705bb48Bc8d36c761fB51bA79d931cA9eb8","status":"false"}] - [traceId=0f43f879-2c9c-4ef3-817b-5c47e49deb25]

2024-12-05T05:29:18.349Z [info] [Server] safeHandler - errorMessage=There are currently no pending contracts. | errorStack=undefined - [traceId=7bfb81c5-7fc2-4a3d-9a93-604bccc8fb17]
```

Looking forward to the feedback on this issue, thank you.

**Comment by kuzdogan** [comment] 2024-12-05 07:28
Hi thanks for reporting. 

When you add the contract to the UI does it show again when you refresh the page? Can you share the full log after you start the server, you add the contract, and try verifying? (Leaving out API keys etc.)

**Comment by wfkhrrzi** [comment] 2024-12-05 10:13
> When you add the contract to the UI does it show again when you refresh the page?

No, the added contract does not appear again after page refresh as shown in this [video](https://github.com/user-attachments/assets/4e548079-e1ed-4dea-a6d4-e64a32155c33)

> Can you share the full log after you start the server, you add the contract, and try verifying?

Here is the full log: [_sourcify-server_logs.txt](https://github.com/user-attachments/files/18021387/_sourcify-server_logs.txt)

**Comment by kuzdogan** [comment] 2024-12-05 14:08
My first guess is this is a CORS issue. Can you please try adding this to your `local.js` config?

```js
  corsAllowedOrigins: [
    /^https?:\/\/(?:.+\.)?sourcify.dev$/, // sourcify.dev and subdomains
    /^https?:\/\/(?:.+\.)?sourcify.eth$/, // sourcify.eth and subdomains
    /^https?:\/\/(?:.+\.)?sourcify.eth.link$/, // sourcify.eth.link and subdomains
    /^https?:\/\/(?:.+\.)?ipfs.dweb.link$/, // dweb links used by Brave browser etc.
    /^https?:\/\/localhost(?::\d+)?$/, // localhost on any port
    /^https?:\/\/192\.168(?:\.\d{1,3}){2}(?::\d+)?$/, // local IPs with 192.168.x.x
    /^https?:\/\/10(?:\.\d{1,3}){3}(?::\d+)?$/, // local IPs with 10.x.x.x
  ],
  ```

**Comment by wfkhrrzi** [comment] 2024-12-05 14:40
The error still persists: [_sourcify-server_logs (1).txt](https://github.com/user-attachments/files/18024830/_sourcify-server_logs.1.txt)

**Comment by kuzdogan** [comment] 2024-12-05 14:49
Ok can you try changing 

```
    "storeType": "database"
```

to 

```
    "storeType": "memory"
```

**Comment by wfkhrrzi** [comment] 2024-12-05 15:12
Still returns the same error after changing storeType to `memory`

```
> sourcify-server@2.4.0 start
> node ./dist/server/cli.js
2024-12-05T15:08:31.097Z [warn] [Server] Overriding default chains: using sourcify-chains.json instead of sourcify-chains-default.json
2024-12-05T15:08:31.734Z [info] [Server] SourcifyChains.Initialized - supportedChainsCount=4 | allChainsCount=4 | supportedChains=[1337,31337,56,97] | allChains=[1337,31337,56,97]
2024-12-05T15:08:31.735Z [info] [Server] Using local solidity compiler
2024-12-05T15:08:31.735Z [info] [Server] Starting server with config - config={
  "serverUrl": "http://localhost:5555",
  "server": {
    "port": 5555,
    "maxFileSize": 31457280
  },
  "storage": {
    "read": "SourcifyDatabase",
    "writeOrWarn": [
      "RepositoryV1"
    ],
    "writeOrErr": [
      "RepositoryV2",
      "SourcifyDatabase"
    ]
  },
  "repositoryV1": {
    "path": "/home/sourcify/app/data/repository"
  },
  "repositoryV2": {
    "path": "/home/sourcify/app/data/repositoryV2"
  },
  "solcRepo": "/home/sourcify/app/data/compilers/solc",
  "solJsonRepo": "/home/sourcify/app/data/compilers/soljson",
  "session": {
    "secret": "j0vKfnLTdzy9YkKiUNqDJiV58YmOgmF4",
    "maxAge": 43200000,
    "secure": false,
    "storeType": "memory"
  },
  "lambdaCompiler": {
    "enabled": false,
    "functionName": "compile-production:3"
  },
  "initCompilers": false,
  "corsAllowedOrigins": [
    "/^https?:\\/\\/(?:.+\\.)?sourcify.dev$/",
    "/^https?:\\/\\/(?:.+\\.)?sourcify.eth$/",
    "/^https?:\\/\\/(?:.+\\.)?sourcify.eth.link$/",
    "/^https?:\\/\\/(?:.+\\.)?ipfs.dweb.link$/",
    "/^https?:\\/\\/localhost(?::\\d+)?$/",
    "/^https?:\\/\\/192\\.168(?:\\.\\d{1,3}){2}(?::\\d+)?$/",
    "/^https?:\\/\\/10(?:\\.\\d{1,3}){3}(?::\\d+)?$/"
  ],
  "verifyDeprecated": false,
  "rateLimit": {
    "enabled": false,
    "whitelist": [

      "10.",
      "::ffff:10.",
      "127.0.0.1",
      "::ffff:127.0.0.1",
      "::1"
    ],
    "windowMs": 1000,

    "max": 2
  }
}
2024-12-05T15:08:31.736Z [warn] [Server] Using memory based session. Don't use memory session in production!
2024-12-05T15:08:31.737Z [info] [Server] Server port set - port=5555
2024-12-05T15:08:31.743Z [debug] [Server] Initializing used storage services - storageServices=["SourcifyDatabase","RepositoryV1","RepositoryV2","SourcifyDatabase"]
2024-12-05T15:08:31.743Z [debug] [Server] Initializing storage service: SourcifyDatabase
2024-12-05T15:08:31.743Z [debug] [Server] Initializing database pool for SourcifyDatabase
2024-12-05T15:08:31.744Z [debug] [Server] Checking database pool health for SourcifyDatabase
(node:19) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
2024-12-05T15:08:31.929Z [info] [Server] SourcifyDatabase initialized - host=192.168.0.20 | port=5432 | database=sourcify | schema=public
2024-12-05T15:08:31.929Z [debug] [Server] Initializing storage service: RepositoryV1
2024-12-05T15:08:31.929Z [info] [Server] RepositoryV1 initialized - repositoryPath=/home/sourcify/app/data/repository
2024-12-05T15:08:31.929Z [debug] [Server] Initializing storage service: RepositoryV2
2024-12-05T15:08:31.929Z [info] [Server] RepositoryV2 initialized - repositoryPath=/home/sourcify/app/data/repositoryV2
2024-12-05T15:08:31.929Z [debug] [Server] Initializing storage service: SourcifyDatabase
2024-12-05T15:08:32.121Z [info] [Server] Server listening - port=5555
2024-12-05T15:09:18.306Z [debug] [Server] addInputFilesEndpoint
2024-12-05T15:09:18.306Z [debug] [Server] extractFilesFromJSON - files=["000b3772b144048c9e4570770c96fbfa.json"] - [traceId=a47c2416-542f-450c-8d79-3a6f5fd63042]
2024-12-05T15:09:18.320Z [info] [Server] Saved files to session - newFilesCount=1 | inputSize=2950136 | sessionInputFilesLength=1 | sessionId=AqkJ6LBXbqp_J_hYhtXlzhKfPERBS0jS - [traceId=a47c2416-542f-450c-8d79-3a6f5fd63042]
2024-12-05T15:09:18.323Z [info] [LibSourcify] Checking files - numberOfFiles=1 - [traceId=a47c2416-542f-450c-8d79-3a6f5fd63042]
2024-12-05T15:09:18.329Z [debug] [LibSourcify] Found a hardhat output file - path=000b3772b144048c9e4570770c96fbfa.json - [traceId=a47c2416-542f-450c-8d79-3a6f5fd63042]
2024-12-05T15:09:18.333Z [debug] [LibSourcify] Processing Hardhat file - hardhatFileSize=2212602 - [traceId=a47c2416-542f-450c-8d79-3a6f5fd63042]
2024-12-05T15:09:18.356Z [debug] [LibSourcify] Parsing hardhat file took 21 milliseconds.
2024-12-05T15:09:18.357Z [debug] [LibSourcify] Extracted metadata and sources from hardhat file - metadataFilesCount=26 | sourceFilesCount=27 - [traceId=a47c2416-542f-450c-8d79-3a6f5fd63042]
2024-12-05T15:09:18.358Z [debug] [LibSourcify] Split files - metadataFilesCount=26 | sourceFilesCount=27 - [traceId=a47c2416-542f-450c-8d79-3a6f5fd63042]
2024-12-05T15:09:18.591Z [debug] [LibSourcify] Checking contract - foundSourcesCount=1 | missingSources=[] | invalidSources=[] - [traceId=a47c2416-542f-450c-8d79-3a6f5fd63042]
2024-12-05T15:09:18.592Z [debug] [LibSourcify] Checking contract - foundSourcesCount=1 | missingSources=[] | invalidSources=[] - [traceId=a47c2416-542f-450c-8d79-3a6f5fd63042]

...

2024-12-05T15:09:18.603Z [debug] [Server] verifyContractsInSession: not verifiable - contractId=69e888058ffabce25f6df298b44472e9a79a3d04 - [traceId=a47c2416-542f-450c-8d79-3a6f5fd63042]
2024-12-05T15:09:18.603Z [debug] [Server] verifyContractsInSession: iterate contract - contractId=22c385016eee22bb6f846f1b729224cae5c2bb26 | contract=ILockPEIC | address=undefined | chainId=undefined - [traceId=a47c2416-542f-450c-8d79-3a6f5fd63042]
2024-12-05T15:09:18.603Z [debug] [Server] verifyContractsInSession: not verifiable - contractId=22c385016eee22bb6f846f1b729224cae5c2bb26 - [traceId=a47c2416-542f-450c-8d79-3a6f5fd63042]
2024-12-05T15:09:18.603Z [debug] [Server] verifyContractsInSession: iterate contract - contractId=d2ac32c38e547da1e37dd6300c324c8b22f05e34 | contract=IPAProfitSharePool | address=undefined | chainId=undefined - [traceId=a47c2416-542f-450c-8d79-3a6f5fd63042]
2024-12-05T15:09:18.603Z [debug] [Server] verifyContractsInSession: not verifiable - contractId=d2ac32c38e547da1e37dd6300c324c8b22f05e34 - [traceId=a47c2416-542f-450c-8d79-3a6f5fd63042]

05T15:09:18.603Z [debug] [Server] verifyContractsInSession: iterate contract - contractId=5949b4d3f7ca0950dcbfe18136e0d9b66b7f90ff | contract=IPancakeRouter01 | address=undefined | chainId=undefined - [traceId=a47c2416-542f-450c-8d79-3a6f5fd63042]
2024-12-05T15:09:18.604Z [debug] [Server] verifyContractsInSession: not verifiable - contractId=5949b4d3f7ca0950dcbfe18136e0d9b66b7f90ff - [traceId=a47c2416-542f-450c-8d79-3a6f5fd63042]
2024-12-05T15:09:26.900Z [debug] [Server] checkAllByChainAndAddresses - chainIds=["1337","31337","56","97"] | addresses=["0xf220f121febaf3B1fd546d07e459FA170A49de84"] - [traceId=2f1f7432-b28d-44b0-943e-9e8ca6f8e172]
2024-12-05T15:09:26.917Z [debug] [Server] Result checkAllByChainAndAddresses - resultArray=[{"address":"0xf220f121febaf3B1fd546d07e459FA170A49de84","status":"false"}] - [traceId=2f1f7432-b28d-44b0-943e-9e8ca6f8e172]
2024-12-05T15:09:36.532Z [info] [Server] safeHandler - errorMessage=There are currently no pending contracts. | errorStack=undefined - [traceId=68b4800d-8187-47d0-a0fc-e08198b58969]
```

**Comment by kuzdogan** [comment] 2024-12-05 17:01
Let's check if the session is being stored in the browser in the first place, and if so check the DB.

After you drag the files onto the UI, can you check if there's a cookie entry called `sourcify_vid` in your browser? This should container the sessionId and match the one in the logs
![image](https://github.com/user-attachments/assets/1667e4ab-d7fd-46c7-a1a2-7f60e5e1f46f)

After that let's check if the session is saved in the database. Assuming you are running the Postgres on docker:

```
docker exec -it database-db-1 psql -U sourcify -d sourcify  -x -c "SELECT * FROM public.session;"
```

where `database-db-1` is the container name `-U sourcify` is the database user and `-d sourcify` is the database's name.

**Comment by wfkhrrzi** [comment] 2024-12-05 17:43
Session id from the logs: `QMbNhehb1J1dCLodWw9Pksrguo7CUPgU`
![image](https://github.com/user-attachments/assets/e3c61d0f-2fdd-4299-b6df-b9c711bf50c2)

`sourcify_vid` cookie: `s%3AY6P4Dz04P2sJKcO8uQzXu9ergQ63zWIh.I54WrRZSvVj2mhl%2F35fuO%2B3p1CMccJOmStiDvXXy640`
![image](https://github.com/user-attachments/assets/48780b8c-71d7-4f4f-867f-58ee85189db3)

Yeah the sessions arent the same

**Comment by kuzdogan** [comment] 2024-12-06 08:31
Ok I was able to reproduce this. The reason this is happening is because you are accessing the UI and server from different IPs/domains. In your case, I can see the server is `192.168.0.20` and you are likely accessing the UI from `localhost:3000`. In that case, since the hosts are different, your session cookie will not be saved because of the cookie setting `SameSite=lax`. Chrome unfortunately does not raise anything about this in error messages (Firefox does)

The easiest solution is to access the server and the UI from the same host: either both `localhost` or both `192.168.0.20`.

We can add an option to allow the Cookies with different hosts with `SameSite=None` but then the connection needs to be HTTPS which is not the case in your local setup.

Let me know if this solves the issue for you or you need another workaround.

**Comment by wfkhrrzi** [comment] 2024-12-06 17:15
Yes finally able to get it working. TYSM for your help!

**Comment by kuzdogan** [comment] 2024-12-06 18:46
Perfect great to hear that :) I'm closing this but feel free to comment here or reach out in our chat channels.

> One more question, how do I get the site to work using a different domain? Do I just add the domain to the CORS list?

Yes that should be sufficient. This is only for session endpoints. The rest do not require any CORS

**Closed by kuzdogan** 2024-12-06 18:46 UTC
