### ISSUE TITLE
Fail to run Sourcify from Docker containers

### ISSUE THREAD

**Issue by svienot** [ethereum/sourcify#998] opened 2023-04-24 18:07 UTC
I am trying to run locally from containers.
- cloned the repo
- created `environments/.env` from `environments/.env.`dev
- made these changes in `.env`:
```
# Server config
REPOSITORY_PATH=/Users/svienot/GIT/ethereum/sourcify/repository
SOLC_REPO=/Users/svienot/GIT/ethereum/sourcify/solc-bin/linux-amd64
SOLJSON_REPO=/Users/svienot/GIT/ethereum/sourcify/solc-bin/soljson
…
# Docker config
## Where to mount the downloaded compilers directory on the host machine
SOLC_REPO_HOST=/Users/svienot/GIT/ethereum/sourcify/solc-bin/linux-amd64
SOLJSON_REPO_HOST=/Users/svienot/GIT/ethereum/sourcify/solc-bin/soljson
…
SERVER_URL=http://localhost
```
- ran this:   ` $ docker-compose -f repository.yaml -f server.yaml -f ui.yaml up -d`

Services start fine, nothing too suspicious in the logs, but when I try to use the _Verifier_, I get the following error:

<img width="1040" alt="Screenshot 2023-04-24 at 19 52 12" src="https://user-images.githubusercontent.com/16097111/234079636-2632a969-ef07-44cc-91e1-9a43ed63aae7.png">

**Comment by kuzdogan** [comment] 2023-04-25 12:39
Hello

I was able to reproduce your error, I think. Can you please check your browser console? You'll see the following error:
<img width="565" alt="image" src="https://user-images.githubusercontent.com/13069972/234276959-400dc1fd-81a7-4e29-b737-a717dc9f8fac.png">

This is because the uploaded docker container you're running has environments variables in `ui/.env.production` set in build time. I.e. when we have built these containers  `REACT_APP_SERVER_URL=https://staging.sourcify.dev/server/` was set and this is injected in the frontend bundle. You can see it if you search the `/usr/share/nginx/html/static/js/main.bd256e5f.js` file inside the `ui` container. 

Do you want to run Sourcify locally? If so I'd suggest following the "Running Sourcify locally" instructions in docs. If you need containers, you should be able to run the other containers but build the UI container locally because unlike others, there's no way to inject environment variables in an already built React app. This needs to be done before the build.

**Comment by svienot** [comment] 2023-04-25 15:12
Hi @kuzdogan
I confirm I see that error in the browser console.
Yes I am trying to run a local version of Sourcify to do some testing/prototyping of contract verification on Hedera and would like to do that on a shared server for convenience (hence Docker).

To make sure to run the UI container built locally I assume I need to:
- remove the ui-latest docker image
- execute `docker-compose -f build-ui.yaml up -d`

But I am not sure at this point which  of the various .env files I should edit to correct my problem ?

**Comment by svienot** [comment] 2023-04-25 17:46
@kuzdogan: I gave up running in Docker for now, just trying to run a development build on my server.
For some reason configuring URLs with localhost does not work, so I am trying the host IP address instead.
So, the repository/server/ui all are running on that server, and I am getting this CORS error when opening the Verifier UI:

<img width="905" alt="Screenshot 2023-04-25 at 19 45 30" src="https://user-images.githubusercontent.com/16097111/234359401-99a9444c-13f5-4ca2-9ad9-6b9a0ea6fee5.png">

Any clue ?

**Comment by kuzdogan** [comment] 2023-04-26 07:38
Ok looks like you were able to pass the correct `SERVER_URL` etc. to the UI. These are in `ui/.env.development` when running with `npm start` and `ui/.env.production` when building the UI. These should be present when running the container `build-*.yaml`. 

Secondly you need to set the server CORS settings in [config.ts](https://github.com/ethereum/sourcify/blob/staging/src/config.ts#L44-L50). For the session endpoint we only allow `sourcify.dev` domains and locally `localhost`. You should add:
```
/^https?:\/\/164.132.52.6(?::\d+)?$/
```
to the `corsAllowedOrigins` object.

**Comment by svienot** [comment] 2023-04-26 14:56
I confirm I fixed the CORS issue as you suggested. Thanks!
Just to recap, I am now able to run my instance with:
 - repo running from container
 - server running (with my mods to activate Hedera net) in development mode
 - UI running in development mode
 
I am still trying to run everything as containers so, in the mean time, it would help if I could run the server with HTTPS. We have our own front-end running with HTTPS so when it tries to access the server API with HTTP we get a 'Mixed Content' error in the browser.
Is there a way to activate HTTPS for the server in DEV ?

**Comment by svienot** [comment] 2023-04-28 08:55
Thanks @kuzdogan, I think I have what I need for now for prototyping using my own nginx.
I have another question before you close this issue...
I notice that if I provide sources to verify a contract with address `0x000000000000000000000000000000000043ADDB` the Verifier UI re-writes the address to `0x000000000000000000000000000000000043aDDB` (no longer all uppercase).
When I use the server API to query the metadata file, the URL is case sensitive.
So a call to `https://sourcify.dev/server/repository/contracts/full_match/:chainId/:contractAddress/metadata.json`
will work only if the _contractAddress_ is capitalized exactly as expected.
- why is that ?
- how does my app know how to capitalize the contract address to perform that query ?

**Comment by svienot** [comment] 2023-04-28 14:25
Ahhh... finally came across ERC-55... sorry for the noise.

**Comment by kuzdogan** [comment] 2023-05-03 15:13
Yes that is actually to provide case **insensitivity** not the otherway around :) But you still need to provide a checksummed address in some cases e.g. when requesting files directly. See https://github.com/ethereum/sourcify/issues/983

If there are no more issues, feel free to close this

**Comment by svienot** [comment] 2023-05-16 21:56
After a bit of experimenting running in development mode, I am back to trying to run an instance from Docker containers, with minimal code changes, using:
 - off the shelf _repository_ container
 - custom build of _server_ container — to work around CORS problem
 - custom build of _ui_ container — to take into account the configuration from `.env` file
So my instance is launched with: 
`docker-compose -f repository.yaml -f server.yaml -f ui.yaml up -d`

The server is not able to verify a contract:

- I add the .sol source file in the Verifier UI. It says `Metadata file missing` — which is expected.
- I then try to add the metadata.json file. This causes the source file to disappear from the Verifier UI, which says `Files Missing`. The server log contains this error:
```
{"labels":{"event":"Server.ApiReplied","type":"logging"},"level":"info","message":{"api":"/health","parameters":{},"response":{},"status":200},"timestamp":"2023-05-16T21:21:13.400Z"}
Couldn't fetch: https://ipfs.io/ipfs/QmWKGfDgSCwhZ8yReGtxbRZM6x8aiLsbNQn1mC1hHmyYbv 0x812d711901c4bd25b0811634213349ea06c1e21fabe9590401ce1ad6b40f670b HelloWorld.sol
AbortError: The user aborted a request.
    at abort (/home/app/packages/lib-sourcify/node_modules/node-fetch/lib/index.js:1448:16)
    at AbortSignal.abortAndFinalize (/home/app/packages/lib-sourcify/node_modules/node-fetch/lib/index.js:1463:4)
    at AbortSignal.[nodejs.internal.kHybridDispatch] (node:internal/event_target:736:20)
    at AbortSignal.dispatchEvent (node:internal/event_target:678:26)
    at abortSignal (node:internal/abort_controller:292:10)
    at AbortController.abort (node:internal/abort_controller:323:5)
    at Timeout._onTimeout (/home/app/packages/lib-sourcify/build/main/lib/utils.js:8:44)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  type: 'aborted'
}
```

- I try to drag both contract files (metadata + .sol source) at the same time on the Verifier UI (then provide the address + chain). When clicking `Verify` the UI displays an error dialog `There are currently no pending contracts`. The server responds with a 400 error and logs this:

`
{"labels":{"event":"Server.ApiReplied","type":"logging"},"level":"info","message":{"api":"/session/verify-validated","parameters":{"contracts":[{"address":"0x0000000000000000000000000000000000233233","chainId":"295","creatorTxHash":"","verificationId":"0xa728f1d143b1ed6c69905dcfdb3ffa0816394ec7b66137424cba737f9600231f"}]},"response":{"error":"There are currently no pending contracts."},"status":400},"timestamp":"2023-05-16T21:27:12.775Z"}
`

Any clue ?

**Comment by svienot** [comment] 2023-05-19 16:11
> Can you verify contracts with the non-session API?: https://docs.sourcify.dev/docs/api/server/verify/
I have not checked this yet.

> if you'll also have the same error on non-containerized server run
The issue is that I have this problem only when trying to run from containers. When _ui_ and _server_ run in development mode, this does not occur.

**Comment by kuzdogan** [comment] 2023-05-19 21:36
Ok that leads me really thinking that this is something about the session environment variables. Do you have the `SESSION_SECRET` set?

**Comment by svienot** [comment] 2023-05-22 07:02
I have not touched this variable so far -- I still have `SESSION_SECRET=yoursessionsecret` in the `.env` file (which works fine when I run the ui and server with npm).

**Comment by kuzdogan** [comment] 2023-05-23 10:56
No it's in `.env`, and if not set it has a fallback value.

Can you please try to verify with the non-session endpoints?

> Another question: I understand the sourcify server is supposed to work with a local IPFS node to publish data to IPFS. Is it assumed that this is running Kubo ?

If you pass a value to `IPFS_API` it will use that to publish data to IPFS. Yes this assumes you are running a Kubo instance, or possibly another IPFS API running on a cloud etc. Here you'd pass the address and the port of the RPC API https://docs.ipfs.tech/reference/kubo/rpc/#getting-started which is typically `5001`. 

If left blank, no publishing is done. This is separate from the `IPFS_GATEWAY`.

**Comment by svienot** [comment] 2023-05-23 13:38
> Can you please try to verify with the non-session endpoints?
Yes I am going to check this.

Another important question: Is there a way, using the API, to know the date at which the contract verification data was created ?

**Comment by svienot** [comment] 2023-05-25 14:43
I have finally succeeded in running (ui, server, repository) fully from docker containers, at least on my localhost.
Getting the right config of env variables is a bit tricky. I have the feeling that I was unable to get things working as long as I was setting `REPOSITORY_PATH` with an absolute path...

**Comment by marcocastignoli** [comment] 2023-11-06 10:54
Updated the docs, so I'm closing this issue. In the following weeks / months we are going to add more details in the docs after we try to spawn new Sourcify instances

**Closed by marcocastignoli** 2023-11-06 10:54 UTC
