### ISSUE TITLE
Partial match on e2e tests

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#1157] opened 2023-08-28 07:19 UTC
On the end-to-end test https://app.circleci.com/pipelines/github/ethereum/sourcify/4604/workflows/2acb4101-bcc9-4664-a027-f39c5409f573/jobs/25896 the deployed contract has returned a partial hash. 

This is indeed true as the metadata hash of the deployed contract seems to be different than usual.

Perfect match (`0x5e465d5345695380368e7bcec3444Cdf4e404783` on Goerli) vs Partial `0xb2Ce053A0dc72B5C8a283fdFf11dc0Fe330aaB6D` on Sepolia.
```
a264697066735822122008afcc4e79a78af494b58a6191acb153a3e09e9c32ded98aa0c66718a6459aca64736f6c63430006020033
```
```
a26469706673582212207f04acb3539466f3d6377bfe387e7523ebcbc6aabb97eaf97370c0d6eac21fe864736f6c63430006020033
```

We should examine why this is the case as this might be something that affects contracts deployed with Hardhat in general.

**Comment by marcocastignoli** [comment] 2023-10-24 08:44
running `npm run deploy:sepolia` and `npm run deploy-with-salt:sepolia` together can cause a problem:

```
marcocastignoli@... metacoin-source-verify % npm run deploy:sepolia

> metacoin-source-verify@2.0.0 deploy:sepolia
> hardhat run scripts/1_deploy_contracts.js --network sepolia

ProviderError: replacement transaction underpriced
    at HttpProvider.request (/Users/marcocastignoli/Projects/metacoin-source-verify/node_modules/hardhat/src/internal/core/providers/http.ts:88:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at HardhatEthersSigner.sendTransaction (/Users/marcocastignoli/Projects/metacoin-source-verify/node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at ContractFactory.deploy (/Users/marcocastignoli/Projects/metacoin-source-verify/node_modules/ethers/src.ts/contract/factory.ts:111:24)
    at main (/Users/marcocastignoli/Projects/metacoin-source-verify/scripts/1_deploy_contracts.js:7:20)

```

This is what happens when I force the transaction fee higher for one of the two (the `68` you see in the logs is the nonce, equal if they are called together)

![Screenshot 2023-10-24 alle 10 38 10](https://github.com/ethereum/sourcify/assets/10226180/c58ea2b6-3797-4fe7-846f-daadd7343083)

The transaction on the right seems to be stuck. So, in theory, this is not the cause of the problem because if the transaction is stuck the test doesn't continue. But I cannot find any other explanations of why this error is happening.

**Comment by marcocastignoli** [comment] 2023-10-24 08:54
This doesn't replicate what failed in circleci tests. In the tests we have two different addresses, I could have checked it before going down into this rabbit hole 🐰

**Comment by marcocastignoli** [comment] 2023-10-24 10:18
Ok, it was indeed a problem of the hardhat repo:
1. it was taking the wrong build-info file
2. it was sending the wrong chosenContract

fixed with: https://github.com/sourcifyeth/metacoin-source-verify/commit/a56aa5363f8b1397c892855f95dee1e721eab2ac

**Closed by marcocastignoli** 2023-10-24 10:18 UTC
