### ISSUE TITLE
502 Bad Gateway Error while verifying with API

### ISSUE THREAD

**Issue by FreezyEx** [ethereum/sourcify#763] opened 2022-06-28 20:15 UTC
I am trying to verify a contract on BSC Testnet using the api /verify.

This is my POST request:
![image](https://user-images.githubusercontent.com/14966614/176276450-18ad709c-0388-4339-bd95-15c3598685a3.png)

and this is the response:
![image](https://user-images.githubusercontent.com/14966614/176276533-dfe29fa6-4f9f-439e-9f15-1616d2eac649.png)

**Comment by kuzdogan** [comment] 2022-06-28 21:00
Hi I wasn't able to reproduce this. Do you still have the issue? I think it was a server hiccup

**Comment by FreezyEx** [comment] 2022-06-29 08:11
I just tried another time and still same error. Can you please show how you did it? Maybe I am missing something

**Comment by kuzdogan** [comment] 2022-06-29 08:35
This works for me. I can't see any errors anywhere as well.

![image](https://user-images.githubusercontent.com/13069972/176390783-985589a5-1993-468f-bed0-fd1e1edc71c9.png)
[1_Storage (copy).sol.txt](https://github.com/ethereum/sourcify/files/9008753/1_Storage.copy.sol.txt)
[metadata (copy).json.txt](https://github.com/ethereum/sourcify/files/9008754/metadata.copy.json.txt)

Address: 0x656d0062eC89c940213E3F3170EA8b2add1c0143
Chain: 100


Can you maybe share yours?

**Comment by FreezyEx** [comment] 2022-06-29 08:59
These are my data:

address: 0x0CD754172CE3DE9396f44d4c0e4C4e52f864E7c8
chain: 97
chosenContract: 15

File: (of course it should be in json but can't upload json here)
[701188607f1134607a280fe25617dcc0.txt](https://github.com/ethereum/sourcify/files/9008969/701188607f1134607a280fe25617dcc0.txt)

**Comment by kuzdogan** [comment] 2022-06-29 09:36
Ok yes it's crashing when it tries add it to IPFS. Looking into it. Thanks

**Comment by kuzdogan** [comment] 2022-07-06 15:11
Hi again. I kind of figured out where the problem is but wasn't able to reproduce it locally to debug further. Do you happen to have the same issue with another contract?

**Comment by FreezyEx** [comment] 2022-07-08 07:55
> Hi again. I kind of figured out where the problem is but wasn't able to reproduce it locally to debug further. Do you happen to have the same issue with another contract?

Ok I will try and get back to you

**Comment by FreezyEx** [comment] 2022-07-09 14:02
> 0x656d0062eC89c940213E3F3170EA8b2add1c0143

I tried with a smaller code and worked. With the old one I am getting Time Out now.
Btw can you confirm I won't see the verificated source on bscscan?

**Comment by kuzdogan** [comment] 2022-07-11 09:56
It seems to be a rare thing and happens with relatively large contracts with many files. It tries to add the metadata file to IPFS before the file was written on the disk but this actually should be executed in the order. For some reason it does not wait for the synchronous file write. 

I removed the contract from the repository and it is still not getting verified. Will try to look deeper this week.

**Comment by kuzdogan** [comment] 2022-07-15 12:13
Documenting other contracts that had the same issue (no metadata.json and `ENOENT` file not found crash):
```
- partial_match/4/0x430968AB0fbA6c5097c430A51f59CA35d018B5e0/metadata.json'
- partial_match/421611/0xfc9ffA88a07da8AfB2820c0aCA2A0c67f45Ceb17/metadata.json
- partial_match/4/0xff7cE5dfb715049ab57Bad08338C5848981210bB/metadata.json
- partial_match/4/0x5eF903387Af0fF26215a934D2B21E4204939f619/metadata.json
- partial_match/42220/0xC96c78E46169cB854Dc793437A105F46F2435455/metadata.json
- partial_match/4/0xD1D32aa94409E59439364de781b6433Cf540706d/metadata.json
- ```

**Comment by kuzdogan** [comment] 2022-08-04 18:49
Should be fixed with https://github.com/ethereum/sourcify/commit/ffcd5e0a2e25b1c223a3d98178c6e5c3c163aad4

can you try on https://staging.sourcify.dev it is not pushed to production yet

**Comment by kuzdogan** [comment] 2022-08-11 16:48
Merged to production with https://github.com/ethereum/sourcify/pull/775 Closing

**Closed by kuzdogan** 2022-08-11 16:48 UTC

**Comment by FreezyEx** [comment] 2022-10-11 07:27
Nice to know. I will check as soon I can

Il Gio 4 Ago 2022, 20:49 Kaan Uzdoğan ***@***.***> ha scritto:
