### ISSUE TITLE
verifying error with the Remix Sourcify plugin

### ISSUE THREAD

**Issue by ryestew** [ethereum/sourcify#365] opened 2021-02-01 19:28 UTC
I get a JS error when trying to verify a contract deployed to 0x5A7Ccc06D2F8EF7d418628bd81DF79c015286bc3 (on Rinkeby) I get this error:

**this error in the js console:**
main.a2488df71c881a1ccc45.js:11 Uncaught (in promise) Error: Error from IDE : source-verification cannot call getCompilationResult of solidity, because solidity is not activated yet
    at l.<anonymous> (main.a2488df71c881a1ccc45.js:11)
    at Object.<anonymous> (main.a2488df71c881a1ccc45.js:11)
    at l.emit (main.a2488df71c881a1ccc45.js:11)
    at main.a2488df71c881a1ccc45.js:11
    at main.a2488df71c881a1ccc45.js:11
    at Object.next (main.a2488df71c881a1ccc45.js:11)
    at i (main.a2488df71c881a1ccc45.js:11)

**Comment by ryestew** [comment] 2021-02-01 19:49
OK - this is a little silly and I think this won't come up very often because I tried to verify a contract and then switched to a different Remix window to verify the contract - so both I didn't have the metadata in that browser nor did that browser have the compiler turned on.

So maybe we should close this issue.

**Comment by FabijanC** [comment] 2021-02-03 14:02
Sourcify server does everything correctly, the problem is in the files it receives. The plugin does not send the correct files. In your case, the files sent were the metadata.json of the Context contract and the source file of the GetPaid conract.

This is an issue with the plugin; relevant information will be posted to this issue: https://github.com/sourcifyeth/remix-sourcify/issues/50

**Comment by FabijanC** [comment] 2021-02-03 14:04
Ok, I'll close this issue, feel free to reopen it if you think it's necessary.

**Closed by FabijanC** 2021-02-03 14:04 UTC
