### ISSUE TITLE
Verifying Contract on Optimism Etherscan gives an error

### ISSUE THREAD

**Issue by Andriy-Kulak** [ethereum/sourcify#1013] opened 2023-05-04 20:24 UTC
When I try to verify contract from ethererscan, it gives the following error. Please assist:
- https://sourcify.dev/#/verifier

I put in the following options:
- contract address: 0x33c4f8C322679daA12a597c2C1e29c5893Dd0393
- verify via etherscan
- chainId: Optimism (10)

I get error below. can someone assist?

<img width="418" alt="Screenshot 2023-05-04 at 14 22 43" src="https://user-images.githubusercontent.com/12179976/236320680-f855a89f-9bd9-4b52-8b46-d70c5499f628.png">

Contract is verified on optimism: https://optimistic.etherscan.io/address/0x33c4f8C322679daA12a597c2C1e29c5893Dd0393#code

**Comment by kuzdogan** [comment] 2023-05-05 10:35
Hello

Thanks for the report. Apparently, this was caused by an unexpected `sed` behavior when replacing secrets. Basically the Optimistic Etherscan API key was being set wrongly.

Should be fixed with https://github.com/ethereum/sourcify/commit/e2c92d911e47a4ebf7eec03df200c74d77735039

You can check on staging:  https://staging.sourcify.dev/#/verifier  Will be fixed with the next release in production

**Comment by kuzdogan** [comment] 2023-05-10 14:24
Closing as the fix is released and perfectly matched https://repo.sourcify.dev/contracts/full_match/10/0x33c4f8C322679daA12a597c2C1e29c5893Dd0393/

**Closed by kuzdogan** 2023-05-10 14:24 UTC

**Comment by Andriy-Kulak** [comment] 2023-05-10 14:27
@kuzdogan thanks, it works now! :-)
